version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  
  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: IOT
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  mysql:
    image: mysql:8
    container_name: mysql_monitoramento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensores
    ports:
      - "3306:3306"
    volumes:
       - db_data:/var/lib/mysql

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: producer
    depends_on:
      - kafka
    volumes:
      - ./tests:/tests
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: iot-sensores
      SEND_INTERVAL: 1

  spark:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark
    depends_on:
      - kafka
      - mysql
    volumes:
      - ./spark:/opt/spark-app
      - ./tests:/tests
      - ./jars:/opt/spark/jars
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: iot-sensores
      CHECKPOINT_PATH: /tmp/spark-checkpoint
      MYSQL_JAR_PATH: /opt/spark/jars/mysql-connector-j-8.3.0.jar
      MYSQL_URL: jdbc:mysql://mysql:3306/sensores
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_TABLE: leituras
    command:
      [
        "spark-submit",
        "--packages",
        "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0",
        "--jars",
        "/opt/spark/jars/mysql-connector-j-8.3.0.jar",
        "/opt/spark-app/iot_consumer_spark_mysql.py"
      ]

volumes:
   db_data:
